// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

var typefaces = [
    {
      name: "Comic Sans",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/ComicSansSpec3.svg/1733px-ComicSansSpec3.svg.png",
      wikipediaPage: "https://en.wikipedia.org/wiki/Comic_Sans",
      released: 1994,
      classification: "Script"
    },
    {
      name: "Curlz",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/4/46/CurlzSpec.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Curlz",
      released: 1995,
      classification: "Display"
    },
    {
      name: "Courier New",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/3/36/IBMCourier.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Courier_(typeface)#Courier_New",
      released: 1995,
      classification: "Monospaced"
    },
    {
      name: "Consolas",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/d/d5/ConsolasSP.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Consolas",
      released: 2007,
      classification: "Monospaced"
    },
    {
      name: "Gills Sans ",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/4/48/GillSansEG.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Gill_Sans",
      released: 1928,
      classification: "Humanist"
    },
    {
      name: "Frutiger",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/e/e5/FrutigerSpec-1.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Frutiger_(typeface)",
      released: 1976,
      classification: "Humanist"
    },
    {
      name: "Optima",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/7/70/Optima_font_sample.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Optima",
      released: 1958,
      classification: "Humanist"
    },
    {
      name: "Verdana",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/0/01/VerdanaSpecimen.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Verdana",
      released: 1996,
      classification: "Humanist"
    },
    {
      name: "Tahoma",
      sampleImg: "",
      wikipediaPage: "https://en.wikipedia.org/wiki/Tahoma_(typeface)",
      released: 1994,
      classification: "Humanist"
    },
    {
      name: "Droid Sans",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/d/d4/DroidSerifSpecimen.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Droid_(typeface)",
      released: 2008,
      classification: "Humanist"
    },
    {
      name: "Calibri",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Calibri_sample_image.png",
      wikipediaPage: "https://en.wikipedia.org/wiki/Calibri",
      released: 2007,
      classification: "Humanist"
    },
    {
      name: "Segoe UI",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/7/72/Segoe_UI_Example.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Segoe#Segoe_UI",
      released: 2003,
      classification: "Humanist"
    },
    {
      name: "Akzidenz-Grotesk",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/e/e1/AkzidenzGroteskspecAIB1.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Akzidenz-Grotesk",
      released: 1898,
      classification: "Grotesque"
    },
    {
      name: "Helvetica",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/2/28/HelveticaSpecimenCH.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Helvetica",
      released: 1957,
      classification: "Grotesque"
    },
    {
      name: "Univers",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/3/30/Univers_sample_2015.png",
      wikipediaPage: "https://en.wikipedia.org/wiki/Univers",
      released: 1957,
      classification: "Grotesque"
    },
    {
      name: "Arial",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/b/b1/ArialMTsp.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Arial",
      released: 1982,
      classification: "Grotesque"
    },
    {
      name: "Roboto",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/e/e7/Roboto_Font_Sample.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Roboto",
      released: 2011,
      classification: "Grotesque"
    },
    {
      name: "Franklin Gothic",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/3/35/FranklinGothicSP.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Franklin_Gothic",
      released: 1902,
      classification: "Geometric"
    },
    {
      name: "Futura",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/5/50/Futura_Specimen.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Futura_(typeface)",
      released: 1927,
      classification: "Geometric"
    },
    {
      name: "Impact",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/2/2b/ImpactSP.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Impact_(typeface)",
      released: 1965,
      classification: "Grotesque"
    },
    {
      name: "Metro",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/8/87/MetroSpecimen.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Metro_(typeface)",
      released: 1929,
      classification: "Geometric"
    },
    {
      name: "FF DIN",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/c/cd/FFDIN.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/FF_DIN",
      released: 1995,
      classification: "Geometric"
    },
    {
      name: "Century Gothic",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/4/4f/CenturyGothicSpecimen.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Century_Gothic",
      released: 1990,
      classification: "Geometric"
    },
    {
      name: "Avenir",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/0/07/AvenirSP.png",
      wikipediaPage: "https://en.wikipedia.org/wiki/Avenir_(typeface)",
      released: 1988,
      classification: "Geometric"
    },
    {
      name: "Gotham",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/4/4e/GothamSpec.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Gotham_(typeface)",
      released: 2000,
      classification: "Geometric"
    },
    {
      name: "Didot",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/f/f9/DidotSP.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Didot_(typeface)",
      released: 1800,
      classification: "Didone"
    },
    {
      name: "Bodoni",
      sampleImg: "",
      wikipediaPage: "https://en.wikipedia.org/wiki/Bodoni",
      released: 1795,
      classification: "Didone"
    },
    {
      name: "Century Schoolbook",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/8/8b/CenturySchoolbookSAIB.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Century_type_family",
      released: 1918,
      classification: "Didone"
    },
    {
      name: "Garamond",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/6/60/GaramondSpecimenA.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Garamond",
      released: 1495,
      classification: "OldStyle"
    },
    {
      name: "Baskerville",
      sampleImg: "",
      wikipediaPage: "https://en.wikipedia.org/wiki/Baskerville",
      released: 1755,
      classification: "Transitional"
    },
    {
      name: "Caslon",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/e/e5/CaslonSp.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Caslon",
      released: 1725,
      classification: "OldStyle"
    },
    {
      name: "Bembo",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/3/38/ET_Book_sample.png",
      wikipediaPage: "https://en.wikipedia.org/wiki/Bembo",
      released: 1496,
      classification: "OldStyle"
    },
    {
      name: "Times New Roman",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/2/21/Times_New_Roman-sample.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Times_New_Roman",
      released: 1932,
      classification: "Transitional"
    },
    {
      name: "Sabon",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Sabon_lt_std_preview.png",
      wikipediaPage: "https://en.wikipedia.org/wiki/Sabon",
      released: 1967,
      classification: "Transitional"
    },
    {
      name: "Palatino",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Palatino_font_sample.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Palatino",
      released: 1949,
      classification: "Transitional"
    },
    {
      name: "Georgia",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/b/ba/GeorgiaSpecimenAIB.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Georgia_(typeface)",
      released: 1996,
      classification: "Transitional"
    },
    {
      name: "Minion",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/9/90/Minion_opticals_sample.png",
      wikipediaPage: "https://en.wikipedia.org/wiki/Minion_(typeface)",
      released: 1990,
      classification: "Transitional"
    },
    {
      name: "Cambria",
      sampleImg: "https://upload.wikimedia.org/wikipedia/commons/b/bd/CambriaSpecimen.svg",
      wikipediaPage: "https://en.wikipedia.org/wiki/Cambria_(typeface)",
      released: 2005,
      classification: "Transitional"
    }
  ].toSorted(function (a, b) {
      return b.released - a.released | 0;
    });

function classificationString(c) {
  switch (c) {
    case "Monospaced" :
        return "Monospaced";
    case "Humanist" :
        return "Humanist";
    case "Grotesque" :
        return "Grotesque";
    case "Geometric" :
        return "Geometric";
    case "Didone" :
        return "Didone";
    case "Transitional" :
        return "Transitional";
    case "OldStyle" :
        return "Old Style";
    case "Display" :
        return "Display";
    case "Script" :
        return "Script";
    
  }
}

function classificationUrl(c) {
  switch (c) {
    case "Monospaced" :
        return "https://en.wikipedia.org/wiki/Monospaced_font";
    case "Humanist" :
        return "https://en.wikipedia.org/wiki/Sans-serif#Humanist";
    case "Grotesque" :
        return "https://en.wikipedia.org/wiki/Sans-serif#Grotesque";
    case "Geometric" :
        return "https://en.wikipedia.org/wiki/Sans-serif#Geometric";
    case "Didone" :
        return "https://en.wikipedia.org/wiki/Didone_(typography)";
    case "Transitional" :
        return "https://en.wikipedia.org/wiki/Serif#Transitional";
    case "OldStyle" :
        return "https://en.wikipedia.org/wiki/Serif#Old-style";
    case "Display" :
        return "https://en.wikipedia.org/wiki/Display_typeface";
    case "Script" :
        return "https://en.wikipedia.org/wiki/Script_typeface";
    
  }
}

var allTimePeriods = [
  "T_2000",
  "T_1967_T1999",
  "T_1934_T1966",
  "T_1900_1933",
  "T_1800_1899",
  "T_Pre1800"
];

function getTimePeriod(y) {
  if (y >= 2000) {
    return "T_2000";
  } else if (y >= 1967) {
    return "T_1967_T1999";
  } else if (y >= 1934) {
    return "T_1934_T1966";
  } else if (y >= 1900) {
    return "T_1900_1933";
  } else if (y >= 1800) {
    return "T_1800_1899";
  } else {
    return "T_Pre1800";
  }
}

var allClassifications = [
  "Monospaced",
  "Humanist",
  "Grotesque",
  "Geometric",
  "Didone",
  "Transitional",
  "OldStyle",
  "Display",
  "Script"
];

function timePeriodString(t) {
  switch (t) {
    case "T_2000" :
        return "Post 2000";
    case "T_1967_T1999" :
        return "1967 - 1999";
    case "T_1934_T1966" :
        return "1934 - 1966";
    case "T_1900_1933" :
        return "1900 - 1933";
    case "T_1800_1899" :
        return "1800 - 1899";
    case "T_Pre1800" :
        return "Pre 1800";
    
  }
}

function App(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "Typeline",
                              className: "w-32 bg-plain-900 text-amber-500 underline flex flex-row items-center justify-center px-3 font-black text-xl italic"
                            }),
                        allClassifications.map(function (classification, i) {
                              return JsxRuntime.jsx("a", {
                                          children: classificationString(classification),
                                          className: [
                                              "font-bold w-32 py-4 flex flex-col items-center text-white ",
                                              "bg-plain-900"
                                            ].join(" "),
                                          href: classificationUrl(classification)
                                        });
                            })
                      ],
                      className: "flex flex-row sticky top-0 bg-white border-b-2 border-plain-900"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        allTimePeriods.map(function (timePeriod) {
                              return JsxRuntime.jsxs("div", {
                                          children: [
                                            JsxRuntime.jsx("div", {
                                                  children: timePeriodString(timePeriod),
                                                  className: "w-32 font-bold px-3 py-2 bg-plain-800 text-white text-right"
                                                }),
                                            allClassifications.map(function (classification, i) {
                                                  return JsxRuntime.jsx("div", {
                                                              children: typefaces.filter(function (t) {
                                                                      if (t.classification === classification) {
                                                                        return getTimePeriod(t.released) === timePeriod;
                                                                      } else {
                                                                        return false;
                                                                      }
                                                                    }).map(function (t) {
                                                                    if (t.sampleImg === "") {
                                                                      return null;
                                                                    } else {
                                                                      return JsxRuntime.jsxs("a", {
                                                                                  children: [
                                                                                    JsxRuntime.jsx("img", {
                                                                                          className: "border border-plain-900 ",
                                                                                          src: t.sampleImg,
                                                                                          width: "100px"
                                                                                        }),
                                                                                    JsxRuntime.jsx("div", {
                                                                                          children: t.released.toString(),
                                                                                          className: "text-xs font-bold"
                                                                                        })
                                                                                  ],
                                                                                  className: "py-1",
                                                                                  href: t.wikipediaPage
                                                                                });
                                                                    }
                                                                  }),
                                                              className: [
                                                                  "w-32 flex flex-col items-center py-2",
                                                                  i % 2 === 1 ? "bg-plain-100" : "bg-white"
                                                                ].join(" ")
                                                            });
                                                })
                                          ],
                                          className: "flex flex-row"
                                        });
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("span", {
                                      children: "Made by "
                                    }),
                                JsxRuntime.jsx("a", {
                                      children: "Thomas Wright",
                                      className: "text-green-400 font-bold",
                                      href: "https://github.com/thomaswright/type-line"
                                    })
                              ],
                              className: "bg-plain-900 text-white text-xs p-4"
                            })
                      ],
                      className: "flex flex-col divide-y-2 divide-plain-900 "
                    })
              ],
              className: "w-fit"
            });
}

var make = App;

export {
  make ,
}
/* typefaces Not a pure module */
